alias chime_off='sudo nvram SystemAudioVolume=%80'
alias chime_on='sudo nvram -d SystemAudioVolume'
alias bundle_stub='bundle install --binstubs .bundle/bin && rbenv rehash'
alias bx='bundle exec'
alias tm='tmux'
alias tmn='tmux new-session -s'
alias tma='tmux attach-session -t'
alias tmd='tmux detach'
alias tml='tmux ls'
alias tmk='tmux kill-session'
alias bip='bundle exec install --path .bundle'
alias rs='bundle exec rails s'
alias brs='bundle exec rake db:setup'
alias brm='bundle exec rake db:migrate'
