alias chime_off='sudo nvram SystemAudioVolume=%80'
alias chime_on='sudo nvram -d SystemAudioVolume'
alias bundle_stub='bundle install --binstubs .bundle/bin && rbenv rehash'
alias bexec='bundle exec'
alias tm='tmux'
alias tmn='tmux ns -s'
alias tma='tmux as -t'
alias tmd='tmux d'
alias tml='tmux ls'
alias tmk='tmux kill-session'
