alias vag='vagrant'
alias vagup='vagrant up'
alias vagdestroy='vagrant destroy'
alias vagssh='vagrant ssh'
alias vaghalt='vagrant halt'

alias htop='sudo htop'

alias chime_off='sudo nvram SystemAudioVolume=%80'
alias chime_on='sudo nvram -d SystemAudioVolume'

alias bundle_stub='bundle install --binstubs .bundle/bin && rbenv rehash'
alias b='bundle'
alias bx='bundle exec'
alias bi='bundle install --path .bundle'
alias rd='bundle exec rails s'
alias rt='bundle exec rake test'
alias rc='bundle exec rails c'
alias rr='bundle exec rake routes'
alias rds='bundle exec rake db:setup'
alias rdm='bundle exec rake db:migrate'
alias rgc='bundle exec rails g controller'
alias rga='bundle exec rails g assets'
alias rgd='bundle exec rails g decorator'
alias rgg='bundle exec rails g generator'
alias rgh='bundle exec rails g helper'
alias rgml='bundle exec rails g mailer'
alias rgmg='bundle exec rails g migration'
alias rgmd='bundle exec rails g model'
alias rgr='bundle exec rails g resource'
alias rgs='bundle exec rails g scaffold'
alias rgsc='bundle exec rails g scaffold_controller'
alias rgsm='bundle exec rails g session_migration'
alias rgst='bundle exec rails g stylesheets'
alias rgt='bundle exec rails g task'

## Add tmux alias here
alias tm='tmux new-session -s "$(basename "$PWD")"'
alias tma='tmux attach-session -t "$(basename "$PWD")"'
alias tmd='tmux detach'
alias tml='tmux ls'
alias tmk='tmux kill-session'
